PLUGIN_NAME=		    smokeping
PLUGIN_VERSION=		  0.1
PLUGIN_DEVEL=       YES 
PLUGIN_COMMENT=		  SmokePing latency logging system
PLUGIN_DEPENDS=		  smokeping fping
PLUGIN_MAINTAINER=	roman.plessl@prunux.ch

.include "../../Mk/plugins.mk"
